### ISSUE TITLE
请问如何将本Hub内的主题与IBus-Theme-Tools结合使用

### ISSUE THREAD

**Issue by Starrah** [openSUSE/IBus-Theme-Hub#5]
作者您好！非常感谢您的付出，贡献的这一系列很好用的工具！
然而，我使用的过程中遇到了一些问题，很抱歉打扰您，如果您有时间的话，可以稍微指导或提示我一下：
我是**非GNOME用户**，因此无法直接安装[Customize IBus GNOME Shell Extension](https://github.com/openSUSE/Customize-IBus)。我注意到了[IBus-Theme-Tools的README](https://github.com/openSUSE/IBus-Theme-Tools/blob/main/README_CN.md)和[自定义 IBus 操作指南](https://github.com/openSUSE/Customize-IBus/blob/main/GUIDE_CN.md)，提示我非GNOME桌面可以下载GTK主题，然后使用IBus-Theme-Tools从主题中提取IBUS相关的部分，再与其他主题混搭即可。
然而，本仓库中提供的css文件，例如[Blue-Light-科技蓝-浅色-99C1F1.css](https://github.com/openSUSE/IBus-Theme-Hub/blob/main/%E4%BB%BF%E5%BE%AE%E8%BD%AFMicrosoft/Blue-Light-%E7%A7%91%E6%8A%80%E8%93%9D-%E6%B5%85%E8%89%B2-99C1F1.css)，似乎并不是一个完整的GTK主题。我尝试了将这个css文件放在`$HOME/.themes/Blue-Light/gtk-3.0/gtk.css`下，再运行`ibus-theme-tools`时，是能识别到一个名为`Blue-Light`的主题的，但是**提取出的CSS为空**。
我猜测是否是因为，本Hub中提供的css仅仅是Customize IBus GNOME Shell Extension能够理解的格式，而并不是标准的GTK主题格式，或者至少说`ibus-theme-tools`无法理解其内容，所以无法提取出IBus相关的css？
这样的话，请问该如何将本Hub内的主题与IBus-Theme-Tools结合使用呢？或者说，**非GNOME桌面用户有什么办法可以使用本Hub内的主题呢**？

**Comment by HollowMan6** [comment]
你好，感谢提问！最简单的回答是，本Hub内的主题无法应用到非GNOME桌面中。在GNOME桌面里，本仓库里的主题可以直接在Customize IBus GNOME Shell Extension中使用，也无需与IBus-Theme-Tools结合使用。IBus-Theme-Tools存在的意义是从已有的[GNOME Shell主题](https://www.gnome-look.org/browse?cat=134)或者[GTK主题](https://www.gnome-look.org/browse?cat=135)里单独提取出IBus相关的主题配置，从而实现系统主题和IBus主题的混搭，本仓库里的主题则已经是适用于GNOME Shell的（相当于已经提取过的）IBus主题了。

在进一步回答你的问题之前，我希望你明白，[GNOME Shell主题](https://www.gnome-look.org/browse?cat=134)和[GTK主题](https://www.gnome-look.org/browse?cat=135)是两个不一样的东西，两者并不能兼容。IBus在GNOME中的前端直接整合到了GNOME Shell中，从而统一了样式。所以在GNOME桌面里需要使用GNOME Shell主题来自定义IBus显示出来的主题。IBus在其他桌面里使用的是IBus自带的原生GTK前端，所以这里需要使用GTK主题才行。

本Hub中提供的css是GNOME Shell主题，去除了和IBus前端无关的class，因而仅仅适用于GNOME Shell，可以被Customize IBus GNOME Shell Extension加载到系统里。标准的GTK主题格式本仓库没有提供也没有计划提供，你可以到 https://www.gnome-look.org/browse?cat=135 下载到很多可用的GTK主题。

实际上，对于非GNOME桌面，因为我之前给他们提交的PR: https://github.com/ibus/ibus/pull/2327 已经合并了。如果你用的是1.5.27及以上版本，实际上你可以在系统里直接安装你想要的GTK主题，然后直接到ibus-setup里的`Advanced`选项卡里勾选上`use custom theme`以及`use custom icon`, 然后选中你想要的主题就好了。这样就无需用
IBus-Theme-Tools 提取生成新GTK主题了。
![Screenshot from 2023-05-03 19-51-32](https://user-images.githubusercontent.com/43995067/235985389-17af57af-d8df-49ee-8357-86159e39e87b.png)
